name: Minimal Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: contributions-activity.svg
          
          base: "" 
          base_skip: yes
          base_indepth: no
          
          config_order: notable, activity
          
          # ðŸŽ© Notable Contributions
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_repositories: yes
          plugin_notable_indepth: yes
          plugin_notable_types: commit, pull_request
          
          # ðŸ“° Recent Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: pr, commit, issue