name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Her gece güncellenir
  workflow_dispatch:              # Manuel çalıştırma butonu ekler
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Erengun
          template: markdown
          base: header, metadata
          
          # Önemli Katkılar (Notable Contributions) Bölümü
          plugin_notable: yes
          plugin_notable_from: organization # Sadece organizasyon depolarını göster (Flutter, Riverpod vb.)
          plugin_notable_types: commit, pull_request
          plugin_notable_indepth: yes # Daha detaylı tarama yapar
          
          # Diller ve Diğerleri
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: percentage