name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Runs every midnight
  workflow_dispatch:              # Allows you to run it manually
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Options
          user: Erengun
          template: classic
          base: header, activity, community, repositories, metadata
          
          # Plugin: Notable (Shows your contributions to big projects)
          plugin_notable: yes
          plugin_notable_from: organization # Only show contributions to orgs
          plugin_notable_types: commit, pull_request
          plugin_notable_indepth: yes
          
          # Plugin: Follow-up (Shows PR status)
          plugin_followup: yes
          plugin_followup_sections: user
          
          # Plugin: Languages (Shows your Flutter/Dart focus)
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_details: bytes-size, percentage